### ISSUE TITLE
How do i Fix the Pathing issue?

### ISSUE THREAD

**Issue by athan1985** [Kaedrin/warhammer-mod-manager#40]
So i have noticed a problem that happened a few days ago about moving the game to another folder or drive would cause a bug to make the mod manage unable to tell the path of the game, i ran into this problem right after the topic was closed, then i saw the reply of it is going to be fixed. At this point of time i am still experiencing this issue, can some one help me with fixing this please?
![image](https://user-images.githubusercontent.com/49864799/56496094-34d7f980-654c-11e9-8290-ec8d3ff58ddb.png)
Here's a picture of the mod manager.

**Comment by kapinow** [comment]
same problem here

**Comment by iienigma** [comment]
I have this same issue.

**Comment by moon234** [comment]
same issue

**Comment by kapinow** [comment]
bump

**Comment by Memeiemiester** [comment]
Same

**Comment by fishrobe** [comment]
Bump because this is still open and it's happening to me. Moved TWWH2 to a different drive, and now I get the pathing issue. Supposedly fixed in the last update, but apparently not.

**Comment by ArnieV** [comment]
Still facing this problem. Can't play TWWH2 otherwise. Damn CA and their launcher...

**Comment by whatisc** [comment]
Hi everyone,

Simply deleting the %appdata%/Kaedrin Mod Manager folder, where the gamedata.xml still incorrectly uses the wrong file paths, will result in your mod manager executing the "first time" search again, and enabling the mod manager again.
